spring:
  application:
    name: namastack-outbox-example-jdbc

  datasource:
    url: jdbc:h2:mem:demo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:

namastack:
  outbox:
    instance:
      graceful-shutdown-timeout-seconds: 2
    jdbc:
      schema-name: myschema
      table-prefix: prefix_
      schema-initialization:
        enabled: false

logging:
  level:
    root: warn
    io.namastack.demo: debug
    org.hibernate.sql: debug
