spring:
  application:
    name: namastack-outbox-basic-example

  datasource:
    url: jdbc:mariadb://localhost:33306/outbox_example
    username: username
    password: password

  jpa:
    hibernate:
      ddl-auto: validate

outbox:
  schema-initialization:
    enabled: true

logging:
  level:
    root: info
    io.namastack: debug
