spring:
  application:
    name: namastack-outbox-example-mariadb

  datasource:
    url: jdbc:mariadb://localhost:33306/outbox_example
    username: username
    password: password

  jpa:
    hibernate:
      ddl-auto: create-drop

namastack:
  outbox:
    instance:
      graceful-shutdown-timeout-seconds: 2

logging:
  level:
    root: info
    io.namastack.demo: debug
