[versions]
# Kotlin and Plugin versions
kotlin = "2.2.21"
springBoot = "4.0.2"
dependencyManagement = "1.1.7"
dokka = "2.1.0"

[libraries]
# Kotlin dependencies
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }

# Spring Boot dependencies
spring-boot-bom = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "springBoot" }
spring-boot = { module = "org.springframework.boot:spring-boot" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-starter-logging = { module = "org.springframework.boot:spring-boot-starter-logging" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux" }
spring-boot-starter-data-r2dbc = { module = "org.springframework.boot:spring-boot-starter-data-r2dbc" }

# Common dependencies
jackson-module-kotlin = { module = "tools.jackson.module:jackson-module-kotlin" }
commons-codec = { module = "commons-codec:commons-codec" }

# JPA and Database dependencies
postgresql = { module = "org.postgresql:postgresql" }
r2dbc-postgresql = { module = "org.postgresql:r2dbc-postgresql" }

# Metrics dependencies
micrometer-registry-prometheus = { module = "io.micrometer:micrometer-registry-prometheus" }

[plugins]
# Kotlin plugins
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }

# Spring plugins
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "dependencyManagement" }

