spring:
  application:
    name: namastack-outbox-performance-test-producer
  r2dbc:
    url: r2dbc:postgresql://localhost:6432/outbox_performance_test
    username: username
    password: password
    pool:
      initial-size: 10
      max-size: 30
      max-idle-time: 30s

server:
  port: 8082
