global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'processor'
    dns_sd_configs:
      - names:
          - 'processor.loadtest.internal'
        type: 'A'
        port: 8081
    metrics_path: '/actuator/prometheus'
