# nonk8s
apiVersion: 1

datasources:
  - name: CloudWatch
    uid: cloudwatch
    type: cloudwatch
    access: proxy
    jsonData:
      defaultRegion: eu-central-1

  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus.loadtest.internal:9090
    isDefault: true
