spring:
  application:
    name: namastack-outbox-example-postgresql

  datasource:
    url: jdbc:postgresql://localhost:5432/outbox_example
    username: username
    password: password

  jpa:
    hibernate:
      ddl-auto: create-drop

outbox:
  instance:
    graceful-shutdown-timeout-seconds: 2

logging:
  level:
    root: info
    io.namastack: debug
