name: namastack-outbox CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        java: [ '17', '21', '25' ]
    name: Java ${{ matrix.java }} tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: oracle

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build and run tests
        run: ./gradlew clean build

      - name: Upload coverage report (artifact)
        if: matrix.java == '21'
        uses: actions/upload-artifact@v6
        with:
          name: jacoco-coverage
          path: build/reports/jacoco/testCodeCoverageReport/html

      - name: Upload coverage report to Codecov
        if: matrix.java == '21'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.xml
          flags: jdk-${{ matrix.java }}
          name: coverage-${{ matrix.java }}

      - name: Publish to Maven
        if: github.ref == 'refs/heads/main' && matrix.java == '21'
        env:
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_signingInMemoryKey }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.ORG_GRADLE_PROJECT_signingInMemoryKeyId }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ORG_GRADLE_PROJECT_signingInMemoryKeyPassword }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.ORG_GRADLE_PROJECT_mavenCentralUsername }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.ORG_GRADLE_PROJECT_mavenCentralPassword }}
        run: ./gradlew publishToMavenCentral -Prelease=false --no-daemon
