spring:
  application:
    name: namastack-outbox-example-sqlserver

  datasource:
    url: jdbc:sqlserver://localhost;databaseName=outbox_example;encrypt=true;trustServerCertificate=true
    username: username
    password: "ThisIsAComplexPassw0rd123!"

  jpa:
    hibernate:
      ddl-auto: validate

outbox:
  schema-initialization:
    enabled: true

logging:
  level:
    root: info
    io.namastack: debug
